### ISSUE TITLE
Allow a datasource to cache (server-side) a history

### ISSUE THREAD

**Issue by antony** [vudash/vudash#41]
Useful for widgets which graph things

Update method can then become

```update({ data, meta, history }) ...```

- [x] Datasources can specify a history length in update-length (i.e. keep last 8 values)
- [x] Widgets can take 'history'
- [x] Statistics widget observes history rather than creating its own
- [x] Old history items are removed from history

**Comment by antony** [comment]
Added in version 8.1.0
