### ISSUE TITLE
Widgets can support data transformation using 'reach'

### ISSUE THREAD

**Issue by antony** [vudash/vudash#42]
Suggest something like

```
{ widget def ...
  transform: {
    reach: 'some.path.to.xyz',
    format: '%2f'
  }
}
```
and removing all previous ability to do this on a per-widget basis.

This would mean declaring only one datasource for an API and then plucking different values for different widgets

- [x] Can specify optional transform clause
- [x] Can specify optional transform 'reach'
- [x] Can specify optional transform 'format'
- [ ] Functionality to format and transform is removed from stock widgets

**Comment by ccollie** [comment]
Was about to add a feature request to integrate [node-jq](https://github.com/sanack/node-jq) as an alternative to reach. This would add tremendous flexibility for munging data from rest endpoints and eliminate or delay the need to create additional datasource a lot of cases.

**Comment by antony** [comment]
Hi @ccollie - thanks for that, I'll look into it!

**Comment by ccollie** [comment]
Here's an approachable tutorial of kinds of transformations possible :
[jq tutorial](https://programminghistorian.org/lessons/json-and-jq).

**Comment by ccollie** [comment]
I took another look at the module and it appears that it actually shells out to the command line. That's unfortunate, because I really like jq. In my case it would be acceptable to use this in our environment since we have a limited number of users, but I'm not sure how this would work in the general case.

**Comment by antony** [comment]
Ah yeah that's certainly not ideal. Perhaps there is a native version (or equivalent) hiding somewhere in npm. If not - I did intend that there were multiple transformation types available, `jq`, `reach` etc, so I don't see why we couldn't support jq as a pluggable module for those who wanted it.

**Comment by antony** [comment]
How about this:

https://github.com/fiatjaf/jq-web

**Comment by ccollie** [comment]
I definitely like the idea of multiple transformation types. Looking at jq-web now.

**Comment by antony** [comment]
Done as #44 and released as Vudash v9.0.0 with a `map` and a `jq` transformer.
