### ISSUE TITLE
Allow global css to be set on dashboard

### ISSUE THREAD

**Issue by antony** [vudash/vudash#6]
- [x] Allows changing of fonts
- [x] Allows changing of colours
- [x] Allows changing of rounding

**Comment by Robertbaelde** [comment]
Is this implemented but not documented? Or will this not be implemented? Would be great to modify some css.

**Comment by antony** [comment]
Hi @Robertbaelde so I implemented this a while ago but I had a big rewrite midway through last year to render everything with svelte. During that process I might have had to drop this functionality.

Having said that, I think it is reasonably easy to re-implement. So I will reopen this issue and set to work on this as soon as possible.
